#!/usr/bin/env python
# Description: Adds every line of the file specified in stdin or in the first
# argument

import sys

if len(sys.argv) <= 1:
    f = sys.stdin
else:
    f = (sys.argv[1], 'r')

sum = 0
for line in f:
    sum += float(line)

print sum

